# Generated by Django 3.1.13 on 2021-08-03 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Dept_Name', models.CharField(max_length=30, unique=True)),
                ('Dept_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Staff_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Emp_Name', models.CharField(max_length=15, unique=True)),
                ('Skills', models.TextField(max_length=40)),
                ('EDept_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='+', to='suv.department')),
            ],
        ),
    ]
